eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        defaultZone: ${eureka_url:http://192.168.0.69:8761/eureka}
  instance:
    hostname: 192.168.178.22
    prefer-ip-address: true
