spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
  datasource:
    url: ${LOCAL_MYSQL_JDBC:jdbc:mysql://localhost:3306/microservice?useSSL=false&serverTimezone=UTC}
    username: ${MYSQL_USER:mysqluser}
    password: ${MYSQL_PASSWORD:55}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
